### ISSUE TITLE
Support for parameters on steps

### ISSUE THREAD

**Issue by richardlawrence** [richardlawrence/Cuke4Nuke#1]

**Comment by dwhelan** [comment]
Richard and I talked about this and it might be best to start with just strings.

Also handling unmatched regex groups might be complexity to be handled later. Perhaps a simply null would suffice?

**Comment by richardlawrence** [comment]
Actually, it turned out to be really easy to support types with an existing registered TypeConverter, so I've built this into my step_definition_parameters branch. This covers most common built-in types. I make the assumption that the regex has the right number of captures and that the matched values will convert to the parameter types declared in the step definition method, which all seems reasonable to me.
