### ISSUE TITLE
Handle multiple concurrent clients

### ISSUE THREAD

**Issue by dwhelan** [richardlawrence/Cuke4Nuke#12]
Not sure if we need this

**Comment by richardlawrence** [comment]
Can you flesh out a scenario where this would be useful? I don't see the value, and it seems to me that assuming one client significantly simplifies things like sharing state between steps.

**Comment by dwhelan** [comment]
Yes, I agree. I was adding it as a placeholder. Bad me. I will close.

**Comment by richardlawrence** [comment]
Not going to implement at this time.
