### ISSUE TITLE
Promotional Screencast

### ISSUE THREAD

**Issue by mattwynne** [richardlawrence/Cuke4Nuke#14]
Screencasts have been a big part of the easy adoption of RSpec and Cucumber in the Ruby community. I think we need a screencast, as soon as Cuke4Nuke is ready, that people can use to (a) see how easy and fun it is to use, (b) give them something to refer to when they're first getting going themselves.

**Comment by mattwynne** [comment]
Does anyone who's got this running fancy doing a quick screencast now Cucumber 0.4.3 is out?

**Comment by richardlawrence** [comment]
I just published a screencast on Cuke4Nuke and WatiN, which is probably one of the top use cases. http://www.richardlawrence.info/2009/12/03/screencast-testing-web-applications-in-net-with-cuke4nuke-and-watin/

**Comment by mattwynne** [comment]
Great stuff. I've added a link on the wiki so I suggest we close this ticket.
