### ISSUE TITLE
Reload assemblies when they change on disk

### ISSUE THREAD

**Issue by aslakhellesoy** [richardlawrence/Cuke4Nuke#17]
This may not be needed if Richard's new launcher launches both the server and cucumber, but here goes...

VS fails to build the assembly if Cuke4Nuke.Server is running. The server has to be stopped and restarted, which means lots of switching and very disrupted flow. Not sure how to implement this though. Just close this ticket if the other solution works better.

**Comment by richardlawrence** [comment]
I was originally thinking that way, but now I believe the all-in-one launcher is a simpler solution.

**Comment by aslakhellesoy** [comment]
Ok, I thought so. Just close this one then.

OT - have you merged my fork? Looks like not on the github web site, but maybe it's just caching too much?

**Comment by richardlawrence** [comment]
I haven't merged your fork yet. I probably won't get back to this project until tomorrow, but it's at the top of my list when I do.

OOT - Have you tried packaging Cucumber with OCRA? Any reason it wouldn't work? Being able to distribute Cucumber and Ruby as a single EXE in the Cuke4Nuke install would simplify adoption tremendously. I'd like people to be able to download a single MSI, install it, and run cuke4nuke.exe (the new wrapper) from the command line anywhere, with the server and Cucumber doing their thing behind the scenes.

**Comment by aslakhellesoy** [comment]
I did use rubyscript2exe a couple of years ago, but OCRA looks nicer. I didn't know about it.

I can give it a stab.
