### ISSUE TITLE
Cuke4Nuke doesn't work with Watin

### ISSUE THREAD

**Issue by lukesmith** [richardlawrence/Cuke4Nuke#19]
I tried using Cuke4Nuke to drive tests using Watin. Watin requires that the current thread have it's ApartmentState set to STA (http://watin.sourceforge.net/apartmentstateinfo.html).

The only way I've got this to work is adding the STAThreadAttribute to the static Main method in the Servers Program class.

Is it possible to add this to Cuke4Nuke, or have it configurable for the Server?

**Comment by richardlawrence** [comment]
Good catch, Luke. It's important to me that Cuke4Nuke work with WatiN, so I'll get this into the next release.

**Comment by lukesmith** [comment]
Thanks Richard.

And another thing, I had to recompile Cuke4Nuke targeting x86 since I'm on a 64bit machine and Watin currently doesn't work running in a 64bit process.

**Comment by richardlawrence** [comment]
Luke: How did you force Cuke4Nuke to target x86? The only option I see in VS is "Any CPU."
