### ISSUE TITLE
cuke4nuke install issue

### ISSUE THREAD

**Issue by bnat** [richardlawrence/Cuke4Nuke#25]
Hello Richard,

```
  I followed your screencast example to setup the cuke4nuke.  I used ruby window installer 
  (“rubyinstaller-1.8.6-p383-rc1”) and the step install cuke4nuke failed for me.  I am using
  Windows Vista Business premium (SP2).  Visual Studio 2008 .NET 3.5

  Here is the actual error when I try to execute the install cuke4nuke

  C:\Ruby>gem install cuke4nuke --no-ri --no-rdoc
```

Building native extensions.  This could take a while...
ERROR:  Error installing cuke4nuke:
        ERROR: Failed to build gem native extension.

C:/Ruby/bin/ruby.exe extconf.rb
checking for strncpy_s()... no
creating Makefile

make
'make' is not recognized as an internal or external command,
operable program or batch file.

Gem files will remain installed in C:/Ruby/lib/ruby/gems/1.8/gems/win32-api-1.4.
5 for inspection.
Results logged to C:/Ruby/lib/ruby/gems/1.8/gems/win32-api-1.4.5/ext/gem_make.ou
t

C:\Ruby>gem list cuke

**\* LOCAL GEMS ***

C:\Ruby>

C:\Ruby\bin>gem list

**\* LOCAL GEMS ***

builder (2.1.2)
cucumber (0.5.3)
diff-lcs (1.1.2)
json_pure (1.2.0)
polyglot (0.2.9)
term-ansicolor (1.0.4)
treetop (1.4.3)
win32console (1.2.0)

C:\Ruby\bin>

Thanks for your help.

**Comment by richardlawrence** [comment]
If you're using the new Ruby installer, you need to install the development kit per the instructions here: http://wiki.github.com/oneclick/rubyinstaller/development-kit. This gives gem the ability to build native extensions. (This extra step is why I haven't changed the Cuke4Nuke wiki to recommend the new installer yet.)

I'm closing this issue. Feel free to reopen it if you still have problems.

Thanks,

Richard

**Comment by bnat** [comment]
Hi Richard, Thank you so much for your help. I can build the native extensions.  But, I am getting an error when try to run the cuke4nuke command inside the project folder.  I got all the folders, files and references added to the project.  

C:\Natarajan\Projects\Cucumber\Google\Google\bin\Debug>cuke4nuke Google.dll
No such file or directory - features (Errno::ENOENT)
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/feature_file.r
b:36:in `initialize'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/feature_file.r
b:36:in`open'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/feature_file.r
b:36:in `source'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/feature_file.r
b:46:in`lang'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/feature_file.r
b:26:in `parse'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/step_mother.rb
:62:in`load_plain_text_features'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/step_mother.rb
:60:in `each'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/step_mother.rb
:60:in`load_plain_text_features'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/cli/main.rb:53
:in `execute!'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/cli/main.rb:23
:in`execute'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/cucumber:8
C:/Ruby/bin/cucumber:19:in `load'
C:/Ruby/bin/cucumber:19

Thanks,

-Nat.

**Comment by rishisharma07** [comment]
Hi,

Any solution for this issues?
I am also facing the above mentioned issue. My environment is exactly the same.
Please suggest.

Thanks,
Rishi

**Comment by richardlawrence** [comment]
You're having the install issue or the run issue? The install issue should be resolved if you follow the instructions above. The run issue is due to running cuke4nuke from the wrong working directory. As with cucumber, there needs to be a features directory below where you run cuke4nuke or you need to specify where the features directory is. Go up two directories and run "cuke4nuke bin\Debug\Google.dll" and everything should work fine.

Richard

**Comment by rishisharma07** [comment]
Thank you Richard, for the help. I also realized the issue and when I supplied the feature directory path while executing the command, I could see all working fine.

Thank you!
