### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by gojko** [richardlawrence/Cuke4Nuke#26]
Adding a Background section breaks Cuke4Nuke. The following Script works OK from Cucumber directly but not from Cuke4Nuke

Feature: Hello World
    In order to ensure that my installation works
    As a Developer
    I want to run a quick Cuke4Nuke test

```
Background:
    Given The Greeting Separator is ,       

Scenario: Hello World
    Given The Action is Hello
    When The Subject is World
    Then The Greeting is Hello, World.

Scenario Outline: Hello World (more complicated)
    Given The Action is <action>
    When The Subject is <subject>
    Then The Greeting is <greeting>.

    Examples:
    |action|subject|greeting|
    |Hello|Mike|Hello, Mike|
    |Jump|Tom|Jump, Tom|
    |Shout|Jim|Shout, Jim|
```

When executed with Cuke4Nuke, it prints:

d:\work\Cuke4NukeExample>Cuke4Nuke bin\Debug\Cuke4NukeExample.dll
Feature: Hello World
        In order to ensure that my installation works
        As a Developer
        I want to run a quick Cuke4Nuke test

  Background:                         # features/basic.feature:6
    Given The Greeting Separator is , # features/basic.feature:7

  Scenario: Hello World                # features/basic.feature:9
    Given The Action is Hello          # Unknown
    When The Subject is World          # Unknown
    Then The Greeting is Hello, World. # Unknown

  Scenario Outline: Hello World (more complicated) # features/basic.feature:14
    Given The Action is <action>                   # Unknown
    When The Subject is <subject>                  # Unknown
    Then The Greeting is <greeting>.               # Unknown

```
Examples:
  | action | subject | greeting    |
  | Hello  | Mike    | Hello, Mike |
  | Jump   | Tom     | Jump, Tom   |
  | Shout  | Jim     | Shout, Jim  |
```

4 scenarios (4 undefined)
16 steps (12 skipped, 4 undefined)
0m0.421s
undefined method `handle_step_failed' for #<Cucumber::WireSupport::WireProtocol::Requests::SnippetText:0x31ae3cc> (NoMethodError)
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/wire_support/wire_packet.rb:28:in`send'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/wire_support/wire_packet.rb:28:in `handle_with'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/wire_support/connection.rb:21:in`call_remote'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/wire_support/request_handler.rb:10:in `execute'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/wire_support/wire_protocol/requests.rb:45:in`execute'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/wire_support/wire_protocol.rb:14:in `snippet_text'
C:/Ruby/lib/ruby/gems/1.8/gems/cucumber-0.5.3/bin/../lib/cucumber/wire_support/wire_language.rb:38:in`snippet_text'

**Comment by richardlawrence** [comment]
Hmm, I use Backgrounds all over the place with Cuke4Nuke. I suspect it's somehow snippet-related, but it would be helpful to see the log of the communication between Cucumber and Cuke4Nuke. Can you please send me the file Cuke4NukeLog.txt from your Cuke4Nuke gem dotnet directory (or at least the relevant section)? Send it to richard at humanizing work dot com if you can't attach it here.

Thanks,

Richard

**Comment by richardlawrence** [comment]
Never mind sending the log. I've been able to reproduce the error with a step with a trailing comma (really any trailing character that isn't allowed in a method name). It's fixed and will be in the next release soon. Thanks!
