### ISSUE TITLE
JSON is not properly escaped for snippets (and possibly other JSON messages)

### ISSUE THREAD

**Issue by aslakhellesoy** [richardlawrence/Cuke4Nuke#29]
Try this undefined step:

Given I have "(.*)" cukes in my belly

When Cuke4Nuke prints snippets I get the following error:

<pre>
Feature: Snippet bug

  Scenario: the bug                       # features\utf8_bug.feature:3
    Given I have "(.*)" cukes in my belly # features\utf8_bug.feature:4

2 scenarios (2 undefined)
4 steps (2 undefined, 2 passed)
0m0.547s
353: unexpected token at '(.*)" cukes in my belly$\")]\npublic void IHaveCukesInMyBelly()\n{\n}"]' (JSON::ParserError)
C:/ruby/lib/ruby/gems/1.8/gems/json_pure-1.2.0/lib/json/common.rb:123:in `parse'
C:/ruby/lib/ruby/gems/1.8/gems/json_pure-1.2.0/lib/json/common.rb:123:in `parse'
C:/ruby/lib/ruby/gems/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/wire_support/wire_packet.rb:8:in `parse'
C:/ruby/lib/ruby/gems/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/wire_support/connection.rb:40:in `fetch_data_from_socket'
C:/ruby/lib/ruby/gems/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/wire_support/connection.rb:20:in `call_remote'
</pre>

I'm not 100% positive that this is a Cuke4Nuke bug. It could also be a bug in the ruby json gem, or in Cucumber's wire protocol. If that's the case, please close this issue and create an issue in Cucumber that links back to this one.

If it is a Cuke4Nuke bug and it turns out to be related to the .NET JSON library, I just came across this one: http://www.infoq.com/news/2010/01/Json-NET - it might (or might not) solve it. In any case it seems fast :-)

**Comment by richardlawrence** [comment]
That's the JSON library I use now. I still need to rip LitJson out of some of the unit tests, but the production code has all been moved to Json.NET.

**Comment by dgfitch** [comment]
I need this, so I'm working on a patch
