### ISSUE TITLE
Support for tables

### ISSUE THREAD

**Issue by richardlawrence** [richardlawrence/Cuke4Nuke#3]

**Comment by shannoncornish** [comment]
Is there any updates as to when Cuke4Nuke will support tables?

**Comment by richardlawrence** [comment]
Probably in the next week. I'm starting work on the .NET side today. 

Note that tables in scenario outlines are already supported (http://wiki.github.com/aslakhellesoy/cucumber/scenario-outlines). This ticket is to add tables in multiline step arguments (http://wiki.github.com/aslakhellesoy/cucumber/multiline-step-arguments ).
