### ISSUE TITLE
How to use Cuke4Nuke on .Net Framework 4.0

### ISSUE THREAD

**Issue by ziobrando** [richardlawrence/Cuke4Nuke#36]
Is there any way to use Cuke4Nuke on Framework 4.0, the platform is a constraint in our current scenario. I keep bumping into the "Unable to contact the wire server" message.

**Comment by richardlawrence** [comment]
Cuke4Nuke.Server.exe is built against 3.5, so it has problems loading 4.0 step definition DLLs with reflection. You can build the project yourself to target 4.0, and it should work fine. 

However, Cuke4Nuke is dying as soon as SpecFlow gets a handful of changes to make it more like the other Cucumber projects (see http://aaftt.agilealliance.org:8080/display/AAFTT/The+Future+of+Cucumber+on+.NET). SpecFlow works nicely on 4.0, so you might consider using that instead.

**Comment by ziobrando** [comment]
Hi Richard, 
Thanks for the quick answer. I was trying also SpecFlow but I preferred the Cuke4Nuke approach. However I am a "guest" on the .Net platform, and looks like the "native majority" has different ideas :-)

I'll try rebuilding the server to have both options open.

Cheers

Alberto
