### ISSUE TITLE
Better feedback from failing steps

### ISSUE THREAD

**Issue by richardlawrence** [richardlawrence/Cuke4Nuke#5]

**Comment by dwhelan** [comment]
What do you have in mind for this? I added a 'backtrace' json parameter so we have a fairly complete exception going back over the wire (no nested exceptions though).

**Comment by richardlawrence** [comment]
I don't know, which is why I prioritized it low. I do know that my code hides a lot of exception detail from Cucumber that may turn out to be useful, so I added this ticket as a placeholder.
