### ISSUE TITLE
An installer that gets all the dependencies so nobody has to know about Ruby unless they want to

### ISSUE THREAD

**Issue by richardlawrence** [richardlawrence/Cuke4Nuke#6]

**Comment by mattwynne** [comment]
A thought I had on a similar line to this was to provide a command that wrapped both the call to start the server and the call to run cucumber too, so people would need to know less about the details.

WDYT?

**Comment by richardlawrence** [comment]
Yeah, I've thought of that, too. I like the idea. Probably should be a separate ticket here.
