### ISSUE TITLE
Support for assertions from test frameworks other than NUnit

### ISSUE THREAD

**Issue by richardlawrence** [richardlawrence/Cuke4Nuke#7]

**Comment by mscottford** [comment]
The [ShouldIt](http://code.google.com/p/shouldit/) library has a really good design for this.

**Comment by mscottford** [comment]
Perhaps we could just ship should it with Cuke4Nuke.

**Comment by dwhelan** [comment]
OK. I think I  am missing something here perhaps as I am new to cucumber. There is nothing in Cuke4Nuke that ties it to NUnit right now. Is the idea that when we flesh out step definition invocation that we would specifically catch assert exceptions and handle them differently than other exceptions?

**Comment by richardlawrence** [comment]
Yes, NUnit, throws exceptions for both passing and failing assertions. I assume other frameworks do the same. We don't want to send an NUnit SuccessException along to Cucumber as a failed step.

**Comment by dwhelan** [comment]
Ok, I get it. It would be a shame to bind Cuke4Nuke to NUnit or any other unit test framework. Perhaps there should be a away for users to inject types of exceptions to treat as pass conditions. Perhaps this is what you have in mind? 

Anyway I don't think this should be a top priority as I don't think this mechanism is used much. I have never used it as it was only provided in quite recent versions of NUnit.

**Comment by dwhelan** [comment]
That ShouldIt library looks interesting! I hope however from my previous comment that we can leave it up to users as to which test framework they want to use.

**Comment by richardlawrence** [comment]
Depending on NUnit isn't as bad as it sounds. We're not requiring anyone to actually use NUnit as a test framework. Rather, we're just borrowing its assertions. Maybe there's a way to include NUnit's assertions as part of Cuke4Nuke.Framework so step definition libraries don't have to reference both NUnit and Cuke4Nuke. (The NUnit license seems to allow this.) I'd rather not create our own assertions if we can avoid it.

**Comment by dwhelan** [comment]
I don't see why Cuke4Nuke needs to have an assertion mechanism. I think the only time an assertion is needed would be in a step definition which users of C4N would write in their own assemblies.

I think it would be an advantage to allow users the choice of assertion mechanism. If I am an MSTest user I might want to us MSTest assertions rather an NUnit's.

If we need to provide special handling for say NUnit's SuccessException then we could provide a mechanism for specifying the types of exceptions to treat as passing w/o needing an explicit dependency on NUnit. The less dependencies the better.

Perhaps there is more to this issue than I am seeing?

**Comment by BenHall** [comment]
I just tried xUnit with the Calc sample and it seems to work OK

```
  | 0       | 40      | add    | 40     |
  Assert.Equal() Failure
  Expected: 40
  Actual:   50 (Xunit.Sdk.EqualException from localhost:3901)
    at CalcFeatures.CalculatorSteps.CheckResult (Double expected) [0x00000] in <filename unknown>:0 
    at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
    at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  examples/Calc/CalcFeatures/features/addition.feature:11:in `Then the result should be <output> on the screen'
```

What is the 'expected' outcome?

**Comment by richardlawrence** [comment]
Yeah, at some point somebody (I assume Declan) pulled out the code around the NUnit SuccessException. I looked through the history the other day and can't find exactly when it happened, why I needed it initially, and why we don't any more. But, yeah, any test framework should work as long as it doesn't throw an exception for success. I'll go ahead and close this issue for now.

**Comment by BenHall** [comment]
That's good! :) 

MSTest, NUnit, xUnit and MbUnit all behave in a very similar way - throw AssertException for failures, SkipExceptions for ignores tests (or similar) - no exception == passed test.
